### ISSUE TITLE
tumblr is starting to go HTTPS

### ISSUE THREAD

**Issue by electricduck** [gedsic/tumbdl#25]
tumblr is now starting to HTTPS, and this script breaks on blogs with HTTPS now.

**Comment by lloyd094** [comment]
Appears to work fine for me - what issues are you running into? I'm currently testing with dnd-5e-homebrew tumblr, (HTTPS) and it looks like it's supposed to.

**Comment by Cool-Programmer** [comment]
Guys i'm having the same issue, script doesn't function when the blog is with HTTPS
Anyone know a solution?

**Comment by lloyd094** [comment]
@electricduck @Cool-Programmer Can you post your system information and tumblr blogs you're having issues with? That might help in determining what's going on.

**Comment by Cool-Programmer** [comment]
I'm using both Windows 10 (64 bit) and Ubuntu 16.04 (64 bit), and tried this script on both of my machines.
The problem is basically with every tumblr blog which is using https protocol, the http ones are working perfectly

**Comment by produnis** [comment]
I have the same problem. But I dont know if it has something to do with https:

All tumblr-blogs have a https://
Some are working just fine with tumbdl, other will just stay empty.

**Comment by jkwlsn** [comment]
I haven't run into issues with HTTPS sites, however I did find the script fails when run from EU IP addresses because it's redirected to the Tumblr GDPR notice. Using a VPN to change your address to outside the EU makes it work perfectly.
